language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-19mode
  - jruby-head
gemfile:
  - gemfiles/Gemfile.rspec-2.x
  - gemfiles/Gemfile.rspec-3.x
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
