language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
gemfile:
  - gemfiles/Gemfile.rspec-2.x
  - gemfiles/Gemfile.rspec-3.x
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
